SELECT * FROM utente where eta > 25;
SELECT * FROM UTENTE WHERE NOME LIKE 'f%';
SELECT * FROM UTENTE WHERE EMAIL LIKE '%gmail%';
SELECT * FROM UTENTE WHERE COGNOME LIKE '%lli';
SELECT * FROM UTENTE WHERE ETA BETWEEN 18 AND 30;
SELECT DISTINCT AUTORE FROM LIBRI;
SELECT * FROM LIBRI WHERE TITOLO LIKE '%AMORE%';
SELECT * FROM LIBRI WHERE ANNO_PUBBLICAZIONE < 1900;
SELECT * FROM LIBRI WHERE ISBN LIKE '_%';
SELECT * FROM PRESTITO WHERE DATA_RESTITUZIONE IS NULL ; 
SELECT * FROM PRESTITO WHERE DATA_PRESTITO BETWEEN '2024-01-01' AND '2024-12-31';
SELECT UTENTE.NOME, UTENTE.COGNOME, PRESTITO.DATA_PRESTITO FROM UTENTE INNER JOIN PRESTITO
ON UTENTE.ID_UTENTE = PRESTITO.ID_UTENTE;
SELECT LIBRI.TITOLO, LIBRI.AUTORE FROM LIBRI JOIN PRESTITO ON PRESTITO.ID_PRESTITO = LIBRI.ID_LIBRO;
SELECT DISTINCT LIBRI.TITOLO FROM LIBRI JOIN PRESTITO ON PRESTITO.ID_LIBRO = LIBRI.ID_LIBRO;
SELECT UTENTE.COGNOME, PRESTITO.ID_PRESTITO FROM PRESTITO JOIN UTENTE ON PRESTITO.ID_UTENTE = UTENTE.ID_UTENTE WHERE UTENTE.COGNOME = 'GALLI';
SELECT PRESTITO.ID_PRESTITO, LIBRI.TITOLO FROM PRESTITO JOIN LIBRI ON LIBRI.ID_LIBRO = PRESTITO.ID_LIBRO WHERE LIBRI.TITOLO LIKE '%STORIA%';
SELECT DISTINCT UTENTE.EMAIL FROM UTENTE JOIN PRESTITO ON PRESTITO.ID_UTENTE = UTENTE.ID_UTENTE;
SELECT LIBRI.TITOLO, LIBRI.ANNO_PUBBLICAZIONE FROM LIBRI JOIN PRESTITO ON PRESTITO.ID_LIBRO = LIBRI.ID_LIBRO WHERE LIBRI.ANNO_PUBBLICAZIONE BETWEEN 1500 AND 1700;
SELECT UTENTE.COGNOME FROM UTENTE WHERE UTENTE.COGNOME LIKE 'b%';
SELECT DISTINCT * FROM LIBRI JOIN PRESTITO ON PRESTITO.ID_LIBRO = LIBRI.ID_LIBRO;
SELECT LIBRI.TITOLO
FROM LIBRI JOIN PRESTITO ON LIBRI.ID_LIBRO = PRESTITO.ID_LIBRO JOIN UTENTE ON PRESTITO.ID_UTENTE = UTENTE.ID_UTENTE WHERE UTENTE.EMAIL = 'nicolo.rossi@gigi.com';
